//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TppkTool.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TppkTool.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This stream has been disposed..
        /// </summary>
        internal static string HiddenStreamName {
            get {
                return ResourceManager.GetString("HiddenStreamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid file path or search pattern..
        /// </summary>
        internal static string InvalidFilePathOrSearchPattern {
            get {
                return ResourceManager.GetString("InvalidFilePathOrSearchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a DDS file..
        /// </summary>
        internal static string NotADdsFile {
            get {
                return ResourceManager.GetString("NotADdsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a NARC file..
        /// </summary>
        internal static string NotANarcFile {
            get {
                return ResourceManager.GetString("NotANarcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a TPPK archive..
        /// </summary>
        internal static string NotATppkArchive {
            get {
                return ResourceManager.GetString("NotATppkArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get the texture id for &apos;{0}&apos;. The texture id is retrieved from the characters after the last underscore in the filename..
        /// </summary>
        internal static string NoTextureId {
            get {
                return ResourceManager.GetString("NoTextureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not contain a TPPK archive..
        /// </summary>
        internal static string NoTppkArchiveInFile {
            get {
                return ResourceManager.GetString("NoTppkArchiveInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This stream does not support reading..
        /// </summary>
        internal static string ReadingNotSupported {
            get {
                return ResourceManager.GetString("ReadingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This stream does not support seeking..
        /// </summary>
        internal static string SeekingNotSupported {
            get {
                return ResourceManager.GetString("SeekingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetLength requires a stream that supports seeking and writing..
        /// </summary>
        internal static string SetLengthRequiresSeekingAndWriting {
            get {
                return ResourceManager.GetString("SetLengthRequiresSeekingAndWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This stream does not support writing..
        /// </summary>
        internal static string WritingNotSupported {
            get {
                return ResourceManager.GetString("WritingNotSupported", resourceCulture);
            }
        }
    }
}
